import bpy  # type: ignore

from .viewport import (
    VIEW3D_MT_WORKSPACE,
    VIEW3D_MT_MODE,
    VIEW3D_MT_VIEWPORT_DISPLAY,
    VIEW3D_MT_SHADING_OPTIONS,
    VIEW3D_MT_SHADING_OPTIONS_CAVITY,
    VIEW3D_MT_RENDERER,
    VIEW3D_MT_VIEW,
    VIEW3D_MT_VIEW_ALIGN,
    VIEW3D_MT_VIEW_VIEW,
    VIEW3D_MT_VIEW_AXIS_ROLL,
    VIEW3D_MT_TRANSFORM_GIZMO,
    VIEW3D_MT_PIVOT_POINT,
)
from .sculpt import (
    VIEW3D_MT_SCULPT_OPS,
    VIEW3D_MT_FACE_SETS,
    VIEW3D_MT_SCULPT_FILTERS,
)
from .select import (
    VIEW3D_MT_SELECT,
    VIEW3D_MT_SELECT_MODE,
    VIEW3D_MT_CURSOR_POSITION,
    VIEW3D_MT_MHE_MODE,
)
from .animation import (
    VIEW3D_MT_ANIMATION_PLAYBACK,
    VIEW3D_MT_ABOUT_FRAMES,
)
from .mesh_ops import (
    VIEW3D_MT_STD_TOOLS,
    VIEW3D_MT_MODIFIERS,
    VIEW3D_MT_APPLY_CLEAR,
    VIEW3D_MT_APPLY,
    VIEW3D_MT_CLEAR,
)

classes = (
    VIEW3D_MT_WORKSPACE,
    VIEW3D_MT_MODE,
    VIEW3D_MT_SCULPT_OPS,
    VIEW3D_MT_VIEWPORT_DISPLAY,
    VIEW3D_MT_SHADING_OPTIONS,
    VIEW3D_MT_SHADING_OPTIONS_CAVITY,
    VIEW3D_MT_RENDERER,
    VIEW3D_MT_VIEW,
    VIEW3D_MT_VIEW_ALIGN,
    VIEW3D_MT_VIEW_VIEW,
    VIEW3D_MT_VIEW_AXIS_ROLL,
    VIEW3D_MT_TRANSFORM_GIZMO,
    VIEW3D_MT_SELECT,
    VIEW3D_MT_SELECT_MODE,
    VIEW3D_MT_CURSOR_POSITION,
    VIEW3D_MT_ANIMATION_PLAYBACK,
    VIEW3D_MT_ABOUT_FRAMES,
    VIEW3D_MT_PIVOT_POINT,
    VIEW3D_MT_FACE_SETS,
    VIEW3D_MT_MHE_MODE,
    VIEW3D_MT_STD_TOOLS,
    VIEW3D_MT_MODIFIERS,
    VIEW3D_MT_SCULPT_FILTERS,
    VIEW3D_MT_APPLY_CLEAR,
    VIEW3D_MT_APPLY,
    VIEW3D_MT_CLEAR,
)


def register():
    for c in classes:
        bpy.utils.register_class(c)


def unregister():
    for c in classes:
        bpy.utils.unregister_class(c)
